<?php

namespace App\Models;

use App\Observers\MiscDepositObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

/**
 *
 */
class MiscDeposit extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'branch_id',
        'gl_account_number',
        'deposit_at',
        'amount',
        'vendor',
        'purpose',
        'user_id',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe( new MiscDepositObserver() );
    }

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo( User::class );
    }// user

    /**
     * @return BelongsTo
     */
    public function branch()
    {
        return $this->belongsTo( PestPacBranch::class, 'branch_id', 'branch_id' );
    }

}// MiscDeposit
